defaults:
  - default
  - _self_

# Override from `default` config
id: crafter_reward
action_repeat: 1
capture_video: False
reward_as_observation: True

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.crafter.CrafterWrapper
  env:
    _target_: crafter.Env
    reward: True
    size: 
      - ${env.screen_size}
      - ${env.screen_size}
    seed: ${seed}
  seed: ${seed}
