defaults:
  - default
  - _self_

# Override from `default` config
id: walker_walk
action_repeat: 1
max_episode_steps: 1000

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.dmc.DMCWrapper
  id: ${env.id}
  width: ${env.screen_size}
  height: ${env.screen_size}
  seed: null
  from_pixels: True
  from_vectors: False
