defaults:
  - default
  - _self_

# Override from `default` config
id: CartPole-v1
mask_velocities: False

# Wrapper to be instantiated
wrapper:
  _target_: gymnasium.make
  id: ${env.id}
  render_mode: rgb_array
