defaults:
  - minecraft
  - _self_

# Override from `minecraft` config
id: open-ended
action_repeat: 1
capture_video: True

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.minedojo.MineDojoWrapper
  id: ${env.id}
  height: ${env.screen_size}
  width: ${env.screen_size}
  pitch_limits:
    - ${env.min_pitch}
    - ${env.max_pitch}
  seed: null
  break_speed_multiplier: ${env.break_speed_multiplier}
  sticky_attack: ${env.sticky_attack}
  sticky_jump: ${env.sticky_jump}
  start_position: null
