# DreamerV3 (Nature version) with the 200M model of the official implementation (`size200m`)

defaults:
  - dreamer_v3_5
  - _self_

dense_units: 1024
cnn_channels_multiplier: 64
world_model:
  discrete_size: 64
  recurrent_model:
    recurrent_state_size: 8192
    hidden_size: 1024
