defaults:
  - dreamer_v3
  - _self_

dense_units: 1024
mlp_layers: 5
world_model:
  encoder:
    cnn_channels_multiplier: 96
  recurrent_model:
    recurrent_state_size: 4096
  transition_model:
    hidden_size: 1024
  representation_model:
    hidden_size: 1024