defaults:
  - dreamer_v3_XL
  - _self_

dense_units: 640
mlp_layers: 3
world_model:
  encoder:
    cnn_channels_multiplier: 48
  recurrent_model:
    recurrent_state_size: 1024
  transition_model:
    hidden_size: 640
  representation_model:
    hidden_size: 640