defaults:
  - dreamer_v3_XL
  - _self_

dense_units: 2
mlp_layers: 1
world_model:
  encoder:
    cnn_channels_multiplier: 1
  recurrent_model:
    recurrent_state_size: 2
  transition_model:
    hidden_size: 2
  representation_model:
    hidden_size: 2