defaults:
  - ppo
  - _self_

name: ppo_recurrent
reset_recurrent_state_on_done: True
max_grad_norm: 0.5
anneal_lr: False
vf_coef: 0.2
clip_coef: 0.2
clip_vloss: True
ent_coef: 0.001
anneal_ent_coef: True
normalize_advantages: True

dense_units: 128
# layer_norm: True
dense_act: torch.nn.ReLU
mlp_layers: 1
rnn:
  mlp_pre_rnn: False
  lstm:
    hidden_size: 64
  mlp:
    bias: True
    layer_norm: ${algo.layer_norm}
    dense_units: ${algo.dense_units}
    activation: ${algo.dense_act}
encoder:
  dense_units: 64

optimizer:
  lr: 3e-4
  _target_: torch.optim.AdamW
