defaults:
  - default
  - _self_

models: 
  world_model:
    model_name: "${exp_name}_world_model"
    description: "DreamerV3 World Model used in ${env.id} Environment"
    tags: {}
  actor:
    model_name: "${exp_name}_actor"
    description: "DreamerV3 Actor used in ${env.id} Environment"
    tags: {}
  critic:
    model_name: "${exp_name}_critic"
    description: "DreamerV3 Critic used in ${env.id} Environment"
    tags: {}
  target_critic:
    model_name: "${exp_name}_target_critic"
    description: "DreamerV3 Target Critic used in ${env.id} Environment"
    tags: {}
  moments:
    model_name: "${exp_name}_moments"
    description: "DreamerV3 Moments used in ${env.id} Environment"
    tags: {}