# @package _global_

defaults:
  - override /algo: a2c
  - override /env: gym
  - override /model_manager: a2c
  - _self_

# Algorithm
algo:
  total_steps: 25000
  rollout_steps: 5
  per_rank_batch_size: ${algo.rollout_steps}
  mlp_keys:
    encoder: [state]

# Buffer
buffer:
  share_data: False
  size: ${algo.rollout_steps}

metric:
  aggregator:
    metrics:
      Loss/value_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Loss/policy_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
