# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_L
  - override /env: diambra
  - _self_

# Experiment
seed: 5
total_steps: 5000000

# Environment
env:
  id: doapp
  num_envs: 8
  frame_stack: 1
  wrapper:
    diambra_settings:
      characters: Kasumi

# Checkpoint
checkpoint:
  every: 200000

# Buffer
buffer:
  checkpoint: True

# Algorithm
algo:
  learning_starts: 65536
  replay_ratio: 0.125
  cnn_keys:
    encoder:
      - frame
  mlp_keys:
    encoder:
      - P1_actions_attack
      - P1_actions_move
      - P1_oppChar
      - P1_oppHealth
      - P1_oppSide
      - P1_oppWins
      - P1_ownChar
      - P1_ownHealth
      - P1_ownSide
      - P1_ownWins
      - stage
