# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_L
  - override /env: diambra
  - _self_

# Experiment
seed: 5
total_steps: 5000000

# Environment
env:
  id: doapp
  num_envs: 8
  frame_stack: 1
  reward_as_observation: True
  wrapper:
    diambra_settings:
      characters: Kasumi

# Checkpoint
checkpoint:
  every: 200000

# Buffer
buffer:
  checkpoint: True

# Algorithm
algo:
  learning_starts: 65536
  replay_ratio: 0.125
  cnn_keys:
    encoder:
      - frame
  mlp_keys:
    encoder:
      - own_character
      - own_health
      - own_side
      - own_wins
      - opp_character
      - opp_health
      - opp_side
      - opp_wins
      - stage
      - timer
      - action
      - reward
    decoder:
      - own_character
      - own_health
      - own_side
      - own_wins
      - opp_character
      - opp_health
      - opp_side
      - opp_wins
      - stage
      - timer
      - action

