# @package _global_

defaults:
  - dreamer_v2
  - override /env: atari
  - _self_

# Environment
env:
  num_envs: 1
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4

# Checkpoint
checkpoint:
  every: 10000

# Buffer
buffer:
  size: 16384
  checkpoint: True

# Algorithm
algo:
  learning_starts: 1024
  per_rank_pretrain_steps: 0
  replay_ratio: 0.0625
  
  dense_units: 8
  mlp_layers: 1
  world_model:
    discrete_size: 4
    stochastic_size: 4
    encoder:
      cnn_channels_multiplier: 2
    recurrent_model:
      recurrent_state_size: 8
    transition_model:
      hidden_size: 8
    representation_model:
      hidden_size: 8
  # # If you want to run this benchmark with older versions,
  # you need to comment the test function in the `./sheeprl/algos/dreamer_v2/dreamer_v2.py` file.
  run_test: False
  # If you want to run this benchmark with older versions,
  # you need to move the `total_steps` config from `algo` to the root.
  total_steps: 16384
