# @package _global_

defaults:
  - override /algo: dreamer_v3
  - override /env: atari
  - _self_

# Experiment
total_steps: 5000000
per_rank_batch_size: 16
per_rank_sequence_length: 64

# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  size: 1000000
  checkpoint: False

# Distribution
distribution:
  type: "auto"
