# @package _global_

# DreamerV3 (Nature version) on the DeepMind Control Suite from pixels (the `dmc_vision` configuration of the official
# implementation, with the 12M model instead of the 200M one: `algo=dreamer_v3_5` for it)

defaults:
  - dreamer_v3_5
  - override /env: dmc
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 4
  action_repeat: 1
  max_episode_steps: -1
  wrapper:
    domain_name: walker
    task_name: walk
    from_vectors: False
    from_pixels: True

# Checkpoint
checkpoint:
  every: 10000

# Buffer
buffer:
  size: 1_000_000
  checkpoint: True
  memmap: True

# Algorithm
algo:
  total_steps: 1_000_000
  cnn_keys:
    encoder:
      - rgb
  mlp_keys:
    encoder: []
  learning_starts: 1024
  # The `train_ratio` of 256 of the official configuration
  replay_ratio: 0.25

# Metric
metric:
  log_every: 5000
