# @package _global_

defaults:
  - override /algo: dreamer_v2
  - override /env: atari
  - _self_

# Experiment
total_steps: 5000000
per_rank_batch_size: 16
per_rank_sequence_length: 50

# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  size: 5000000
  type: sequential
  checkpoint: False
  prioritize_ends: False

# Distribution
distribution:
  type: "auto"