# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_L
  - override /env: minerl
  - _self_

# Experiment
seed: 5
total_steps: 50000000

# Environment
env:
  num_envs: 4
  id: custom_navigate
  reward_as_observation: True
  wrapper:
    multihot_inventory: False

# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  checkpoint: True

# Algorithm
algo:
  replay_ratio: 0.015625
  learning_starts: 65536
  cnn_keys:
    encoder:
      - rgb
  mlp_keys:
    encoder:
      - life_stats
      - inventory
      - max_inventory
      - compass
      - reward
    decoder:
      - life_stats
      - inventory
      - max_inventory
      - compass
