# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_XL
  - override /env: crafter
  - _self_

# Experiment
seed: 5
total_steps: 1000000

# Environment
env:
  num_envs: 1
  id: crafter_reward

# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  checkpoint: True

# Algorithm
algo:
  
  replay_ratio: 0.5
  cnn_keys:
    encoder:
      - rgb
    decoder:
      - rgb
  mlp_keys:
    encoder:
      - reward
    decoder: []
