# @package _global_

defaults:
  - sac
  - override /algo: droq
  - _self_

# Model Manager
model_manager:
  models:
    agent:
      model_name: "${exp_name}"
      description: "DroQ Agent in ${env.id} Environment"
      tags: {}
