# @package _global_

defaults:
  - override /algo: dreamer_v3
  - override /env: minedojo
  - _self_

# Experiment
total_steps: 10000
per_rank_batch_size: 2
per_rank_sequence_length: 4

env:
  num_envs: 1

algo:
  actor:
    _target_: sheeprl.algos.dreamer_v3.agent.MinedojoActor

  learning_starts: 2048
  dense_units: 2
  mlp_layers: 1
  world_model:
    discrete_size: 4
    stochastic_size: 4
    encoder:
      cnn_channels_multiplier: 2
    recurrent_model:
      recurrent_state_size: 4
    transition_model:
      hidden_size: 2
    representation_model:
      hidden_size: 2

# Checkpoint
checkpoint:
  every: 10000

# Buffer
buffer:
  size: 10000
  checkpoint: False

# Distribution
distribution:
  type: "auto"

cnn_keys:
  encoder: [rgb]
  decoder: [rgb]

mlp_keys:
  encoder:
    - inventory
    - inventory_max
    - inventory_delta
    - equipment
    - life_stats
  decoder:
    - inventory
    - inventory_max
    - inventory_delta
    - equipment
    - life_stats