# @package _global_

defaults:
  - override /algo: ppo_np
  - override /env: gym
  - override /fabric: fabric_np
  - _self_

# Experiment
algo:
  total_steps: 65536
  per_rank_batch_size: 64
  mlp_keys:
    encoder: [state]

# Buffer
buffer:
  share_data: False
  size: ${algo.rollout_steps}

metric:
  log_every: 32768