# @package _global_

defaults:
  - ppo
  - override /algo: ppo_recurrent
  - override /model_manager: ppo_recurrent
  - _self_

algo:
  per_rank_num_batches: 4
  per_rank_sequence_length: 8
  total_steps: 409600
  rollout_steps: 256
  update_epochs: 4

# Environment
env:
  id: CartPole-v1
  num_envs: 16
  mask_velocities: True

buffer:
  memmap: False
