# @package _global_

defaults:
  - ppo
  - override /algo: ppo_recurrent
  - _self_

algo:
  rollout_steps: 256
  update_epochs: 16

# Experiment
per_rank_batch_size: 16
per_rank_sequence_length: 64

# Environment
env:
  id: CartPole-v1
