# @package _global_

defaults:
  - override /algo: sac_np
  - override /env: gym
  - override /fabric: fabric_np
  - _self_

# Experiment
algo:
  total_steps: 1000000
  per_rank_batch_size: 256
  mlp_keys:
    encoder: [state]
    decoder: [state]

# Checkpoint
checkpoint:
  every: 50000

# Buffer
buffer:
  size: 1000000
  checkpoint: False
  sample_next_obs: False

# Environment
env:
  id: LunarLanderContinuous-v2
