# @package _global_

defaults:
  - sac
  - override /algo: sac_ae
  - _self_

# Experiment
per_rank_batch_size: 128

# Model Manager
model_manager:
  models: [
    {
      model_name: "${exp_name}_encoder",
      description: "SAC-AE Encoder used in ${env.id} Environment",
      tags: {} 
    },
    {
      model_name: "${exp_name}_decoder",
      description: "SAC-AE Decoder used in ${env.id} Environment",
      tags: {} 
    },
    {
      model_name: "${exp_name}_agent",
      description: "SAC-AE Agent in ${env.id} Environment",
      tags: {} 
    },
  ]

# Environmment
env:
  frame_stack: 3

metric:
  aggregator:
    metrics:
      Loss/reconstruction_loss: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}